#!/bin/bash

gpio mode 14 out
gpio mode 6 out
gpio write 14 0

nohup watch -n30 /opt/tools/hackpi/exec30

#modprobe gpio-sunxi
#echo 0 > /sys/class/gpio_sw/standby_led/data
#echo 0 > /sys/class/gpio_sw/normal_led/data

/opt/tools/hackpi/fireWall
/opt/tools/hackpi/setMac
/opt/tools/hackpi/initAp

/etc/init.d/postgresql start

