#!/bin/bash

# Switch Power Led off and Status (green) led on
modprobe gpio-sunxi
echo 1 > /sys/class/gpio_sw/standby_led/data
echo 0 > /sys/class/gpio_sw/normal_led/data
modprobe -r gpio-sunxi

gpio mode 6 out # Fan control
gpio mode 12 in # initAp Switch detect

/opt/tools/hackpi/initLcd

/opt/tools/hackpi/fireWall
/opt/tools/hackpi/setMac

/etc/init.d/postgresql start

swc=`gpio read 12`
if [[ $swc -eq 0 ]]
 then
  /opt/tools/hackpi/initAp
fi

/usr/bin/nohup /opt/tools/hackpi/checks &> /dev/null &
