#!/bin/bash

if [[ $# -eq 0 ]] || [[ -z $1 ]]
 then
  echo " "
  echo "*** ${0##*/} needs interface argument.  e.g. ${0##*/} wlan0"
  echo " "
  exit 1
fi

if [[ ! -d /sys/class/net/$1 ]] && [[ ! -d /sys/class/net/$1mon ]]
 then
  echo " "
  echo "*** ${0##*/}: Interface $1 does not exist.  Please specify a valid interface."
  echo " "
  exit 1
fi

ifconfig $1 down
killall dhclient
killall wpa_supplicant
airmon-ng start $1
sleep 3
airodump-ng $1mon

